import { notesLoaders } from "./notes/notes.js";

const BASE_URL = "https://raw.githubusercontent.com/GMPranav/Tool-Assisted-Runs/refs/heads/main/";

export const tasProfileData = {
    profile: {
        handle: "GMP",
        hobby: "Tool-Assisted Speedruns",
        bio:
            "Hi, I know one franchise, and you can probably guess what it is based on my activity. " +
            "I got into the formerly niche hobby of speedrunning and still niche hobby of TASing through the PoP speedrunning community.",
    },

    completedProjects: [
        {
            platform: "DOS",
            game: "Prince of Persia",
            branch: "No Major Glitches",
            time: "18:50.82",
            emulator: "JPC-RR 11.8",
            obsolete: false,
            inputFile: { label: "JRSR", href: BASE_URL + "pop1/any_nmg.jrsr" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=qEUwTODtHLk" },
            commentary: null,
            notesLoader: notesLoaders.pop1_any_nmg,
        },
        {
            platform: "DOS",
            game: "Prince of Persia 2: The Shadow and the Flame",
            branch: "Any%",
            time: "14:50.62",
            emulator: "JPC-RR 11.8",
            obsolete: true,
            inputFile: { label: "JRSR", href: BASE_URL + "pop2/any.jrsr" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=WU8xglub3To" },
            commentary: null,
            notesLoader: notesLoaders.pop2_any,
        },
        {
            platform: "DOS",
            game: "Prince of Persia 2: The Shadow and the Flame",
            branch: "Any%",
            time: "14:11.00",
            emulator: "JPC-RR 11.8",
            obsolete: true,
            inputFile: { label: "JRSR", href: BASE_URL + "pop2/any_v2.jrsr", },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=Ga54Iab3NxE" },
            commentary: { label: "YouTube", href: "https://www.youtube.com/watch?v=SMI2d9-YqnI" },
            notesLoader: notesLoaders.pop2_any_v2,
        },
        {
            platform: "DS",
            game: "Prince of Persia: The Fallen King",
            branch: "Any%",
            time: "2:23:31.68",
            emulator: "DeSmuME 0.9.9",
            obsolete: false,
            inputFile: { label: "DSM", href: BASE_URL + "pop_tfk/any.dsm" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=OoPWX30wsGA" },
            commentary: { label: "YouTube", href: "https://www.youtube.com/watch?v=MeJ-Le27JuM" },
            notesLoader: notesLoaders.pop_tfk_any,
        },
        {
            platform: "GBA",
            game: "Prince of Persia: The Sands of Time",
            branch: "Any%",
            time: "28:37.38",
            emulator: "BizHawk 2.7",
            obsolete: false,
            inputFile: { label: "BK2", href: BASE_URL + "pop_sot_gba/any.bk2" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=Gmj8rFkf8do" },
            commentary: { label: "YouTube", href: "https://www.youtube.com/watch?v=df-jXeRRQ1w" },
            notesLoader: notesLoaders.pop_sot_gba_any,
        },
        {
            platform: "Flash",
            game: "The Amazing Dare Dozen",
            branch: "Any%",
            time: "02:35.00",
            emulator: "libTAS + Ruffle",
            obsolete: false,
            inputFile: { label: "LTM", href: BASE_URL + "amazing_dozen/any.ltm", },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=Iqz6mIPe4aQ" },
            commentary: null,
        },
        {
            platform: "Flash",
            game: "Raft Wars",
            branch: "Any%",
            time: "04:45.49",
            emulator: "libTAS + Ruffle",
            obsolete: false,
            inputFile: { label: "LTM", href: BASE_URL + "raftwars/any.ltm" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=clStfO49h0k" },
            commentary: null,
            notesLoader: notesLoaders.raftwars_any,
        },
        {
            platform: "Linux",
            game: "Stick With It",
            branch: "Any%",
            time: "08:00.73",
            emulator: "libTAS 1.4.3",
            obsolete: false,
            inputFile: { label: "LTM", href: BASE_URL + "stick_with_it/any.ltm" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=uk5uxDvvmBE" },
            commentary: null,
            notesLoader: notesLoaders.stick_with_it_any,
        },
        {
            platform: "DOS",
            game: "Prince of Persia 2: The Shadow and the Flame",
            branch: "Any%",
            time: "14:47.45",
            emulator: "libTAS + PCem",
            obsolete: false,
            inputFile: { label: "LTM", href: BASE_URL + "pop2/any_v3.ltm" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=bVoebAC-6GQ" },
            commentary: { label: "YouTube", href: "https://www.youtube.com/watch?v=Ikz2azVfqyc" },
            notesLoader: notesLoaders.pop2_any_v3,
        },
        {
            platform: "GC",
            game: "Prince of Persia: Warrior Within",
            branch: "Zipless",
            time: "24:56.15",
            emulator: "BizHawk + Dolphin",
            obsolete: false,
            inputFile: { label: "DTM", href: BASE_URL + "pop_ww/any_zipless.dtm" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=HyYQD3EYAPk" },
            commentary: null,
            notesLoader: notesLoaders.pop_ww_any_zipless,
        },
        {
            platform: "GC",
            game: "Prince of Persia: The Sands of Time",
            branch: "No Major Glitches",
            time: "1:21:05.15",
            emulator: "BizHawk + Dolphin",
            obsolete: false,
            inputFile: { label: "DTM", href: BASE_URL + "pop_sot/any_nmg.dtm" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=tijiavSRDjI" },
            commentary: { label: "YouTube", href: "https://www.youtube.com/watch?v=dS-zpj31Ers" },
            notesLoader: notesLoaders.pop_sot_any_nmg,
        },
        {
            platform: "GC",
            game: "Prince of Persia: The Sands of Time",
            branch: "Zipless",
            time: "57:37.317",
            emulator: "BizHawk + Dolphin",
            obsolete: false,
            inputFile: { label: "DTM", href: BASE_URL + "pop_sot/any_zipless.dtm" },
            encode: { label: "YouTube", href: "https://www.youtube.com/watch?v=QraeCWf1cjw" },
            commentary: { label: "YouTube", href: "https://www.youtube.com/watch?v=klUmBuYTLmE" },
            notesLoader: notesLoaders.pop_sot_any_zipless,
        },
    ],
};

export default tasProfileData;
