export default `This is the DOS version of Prince of Persia 2: The Shadow and the Flame, second game in the classic franchise which consists games spanning multiple generations.
!!Game objectives
*Emulator used: JPC-RR r11.9.Alpha by c-square (Also syncs on JPC-rr 11.8)
*BIOS used: The BIOS and VGABIOS that come pre-bundled with the emulator was used as instructed in the emulator description page.
*Game Version: IR (Initial Release)
*The objective of the run is to complete the game, which is this case means saving the princess from the evil Jaffar.
*There are plenty of glitches used for various skips and sequence breaks. The most notable one is wall clipping, which is used to skip major portions of various levels. It and the other glitches are explained in the level-wise comments below.
*We control only one character in the run - the prince.
*Hits are taken at some parts of the run as its just faster in those places.
*Restarts are used whenever it means faster movement. The game is saved and reloaded at the start of level 8 to avoid a known crash. The cause of the crash is not understood fully but this is a good workaround that doesn't cost much time.

!!Comments
This is a game which features both plenty of glitches and satisfying movement. Almost all the inputs can be buffered in this game. Unlike its predecessor, this game is relatively more free of RNG, mainly because of the strategies being devised in such a way that enemies are dealt with as little as possible. The wall-clipping glitch was found recently by "Challenger", another Prince of Persia TAS enthusiast. This run uses it a lot, although the possibility of finding even more skips with this in the future. Jumping is the fastest movement when in flat terrain, however depending on the layout of the room, various other movements are done to gain time.
!!Stage by stage comments
! Level 1
Right at the start you can get a glimpse of how its possible to take advantage of the guard AI in this game, as we breeze past through the first set of guards after some special movement to deal with the very first one. As we advance further, we take a hit from a guard to get our swords out quicker and one-shot him. A little further, we hit a checkpoint and immediately restart to cancel the prince's stagger and get up animation which takes quite a while. From there we proceed to escape in the ship. At the right moment, its possible to skip the end level jingle and the cutscene by pressing esc followed by space in quick succession.
! Level 2
This level is arguably the most RNG part of the run. Luckily I didn't get a unlucky tile postion and was able to clear it quickly. The following copy-protection screen needs the correct symbols to be entered. Luckily unlike in the original game it wastes no time (atleast in a TAS) as inputs can be buffered just like in the initial command screen. Its also worth nothing that the space button is used to cancel any sort of fading menus throughout the run.
! Level 3
This level has a shorter path to the exit, but for the completion of this game, we require a total of nine health upgrade potions (including the 3 we have at the start), we will get to the reasons later. After getting to the nearest potion in this level, the wall-clipping is used for the first time in the run to get quick access to an otherwise farther exit door. The way clip works is when standing still close enough to a wall facing away from it, it is possible to run through the wall for a certain distance before it pushes the prince out. but if we do a turn around, the prince gets struck in the wall or comes through the other side if the wall is narrow enough. The good thing is that this process can be rinsed and repeated as many times as we want to clip walls of any width.
! Level 4
Once again this level has a slightly faster way of reaching the exit using a floating potion, but we do a small detour to collect another health upgrade potion. Until pressing the exit button, this level is all about optimised movement. At the end we do a special kind of wall-clip that doesn't require anything special in terms of input execution. For some reason, if a wall clip is performed at the very end of the map, it warps the prince back a couple of rooms in the opposite direction. In this case, it happens so that the prince is still inside the wall, so we clip our way through to left to eventually end our wall journey. From there we simply run to the exit.
! Level 5
At the start of this level we do some specific movement to get past the skeleton and the next section with some contraptions to reach the carpet room. There we do a small clip to skip a small climb up section. After that follows the biggest clip of the run that spans several blocks to reach a room with a health upgrade potion. This skip would be faster regardless of the existence of the potion but we get it as an added bonus in this route, avoiding a sidetrack to get to it. From there we run to the end of the level. We do a little checkpoint restart before the bridge section both to setup a good position for jumping through the skeleton and also because the movement is faster.
! Level 6
This level is the primary reason why the IR version of the game is used. For some reason the starting door of the level is open and allows us to exit straight to the next level.
! Level 7
We start the level with some movement stuff and then get straight to the first clip. Its a very short clip but one of the biggest timesaves of the run as it leads directly to a potion room just like in level 5. After dealing with the medusa head and drinking the potion, we do another little clip to get out of there really quickly. As we proceed further we meet the first sword trap. We avoid having to crawl under them at all costs as its slow so we either bunny hop or in some cases its possible jump through them altogether. In this case we have to do the former. After the dealing with the medusa head in the next room we do another clip to get to the room with the exit door buttons. We can also jump through the trap in that room and also stand close enough to the room with the door without actually having to go through the room transition to exit through it.
! Level 8
We quickly perform a save and load to avoid a known crash in this level. After the climb down at the start, we perform a clip instead of crawling under the hole especially so that can also avoid the trap after with bunny hops, which overall ends up being faster. We jump our way through the the end long corridor where we are conveniently aided by a medusa head to clip through the door. This glitch is possible even without the head but here it just helped even more. We pickup the sword and skip the cutscene. This is where the game would crash if not for the save/load at the start. After that we do specific movement in the next rooms to avoid as many medusa heads as possible to reach the exit.
! Level 9
This level is again fully movement to avoid medusa heads. At the very end, we do a little trick with our sword actions to avoid falling with a falling tile to reach the horse.
! Level 10
The graphics of this level fails to load as we skip the previous cutscene. Luckily the collision/interactions all work normally which is more than enough for us to reach the exit and finish this short level.
! Level 11
This is by far the longest level of the run. First we have a movement section, then we do a little clip to get to the potion quicker. Then after more movement we reach a checkpoint which we restart to stop our momentum quickly. Then we deal with the guards in the next section. First we essentially stall the first guard in a specific position such that his pal lands between him and the prince blocking his way. Before the second guard can recover from his stagger, we manage to get away. Next, we kill the guard in the next section on top of a closing button, which effectively disables it. This allows us to do a skip in our return path. We do more movement, trap dodges, wall-clips to finish the level, the usual stuff.
! Level 12
This level starts straight with a wall clip to avoid going around using the door to the left. We do another clip to skip a small climbing section and then its a straight path to the level exit.
! Level 13
This level starts with some specific movement to tightly get under the door as well setup position for jumping through the sword trap. The rest of the level is just more specific movement to get through the guards by slowing down as little as possible. Near the flame, two cool things. One, the guard just get confused and falls off if we stand at a specific spot before he notices us. And second, we don't have to do the flame shenanigans, we can just return without doing anything with it as the only thing we need is for the trigger to open the exit door to be hit, which is luckily not tied to the flame interaction. Also we pickup a health upgrade potion on the way back to the exit.
! Level 14
In this level, normally we would need to have 11 potions to get to the flame form, which is achieved by continuously turning left and right alternatively. But we can do so with nine potions only with a clever trick. By placing ourselves really close to the cutscene trigger at the start, we can use the cutscene to interrupt the animation of turning into the shadow which is what normally happens if we have only 9 potions. At the end of cutscene, we magically appear in the flame form, albeit in a slightly different graphics which arguably looks cooler. We proceed to take down the clones of Jaffar and then Jaffar himself by following a specific path at the end chase segment.

!!Final Thoughts and acknowledgements
I had quite a lot of fun making this and I hope you will watching this as well :D. I am happy with the result I got but I may return to this in the future to try make some improvements, especially if there are major route changes found. I would like to specially thank eien86, Samabam, Challenger for helping me in routing certain parts, timing the strats, etc and in general the whole RTA speedrunning community for being supportive and just being an awesome community in general.`;